# Generated by Django 5.0.6 on 2024-07-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titulo")),
                ("create_at", models.DateField(auto_now_add=True)),
                ("finished_at", models.DateField(null=True)),
                (
                    "category",
                    models.CharField(
                        default="Opção Padrão", max_length=100, verbose_name="Categoria"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0, verbose_name="Quantidades de Unidades"
                    ),
                ),
            ],
        ),
    ]
