# Generated by Django 5.0.6 on 2024-07-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="title",
        ),
        migrations.AddField(
            model_name="items",
            name="brand",
            field=models.CharField(default="", max_length=100, verbose_name="Marca"),
        ),
        migrations.AddField(
            model_name="items",
            name="location",
            field=models.CharField(
                default="", max_length=100, verbose_name="Localização"
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="model",
            field=models.CharField(default="", max_length=100, verbose_name="Modelo"),
        ),
        migrations.AddField(
            model_name="items",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="Nome"),
        ),
        migrations.AddField(
            model_name="items",
            name="observation",
            field=models.CharField(
                default="", max_length=300, verbose_name="Observação"
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="sub_category",
            field=models.CharField(
                default="", max_length=100, verbose_name="Sub-Categoria"
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="category",
            field=models.CharField(
                default="", max_length=100, verbose_name="Categoria"
            ),
        ),
    ]
