# Generated by Django 5.0.6 on 2024-07-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_remove_items_title_items_brand_items_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="observation",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="Observação"
            ),
        ),
    ]
