# Generated by Django 5.0.6 on 2024-07-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_alter_items_observation"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="locality",
            field=models.CharField(
                default="", max_length=100, verbose_name="Localidade"
            ),
        ),
    ]
