# Generated by Django 5.0.6 on 2024-08-22 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_items_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemsAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("model_name", models.CharField(max_length=100)),
                ("record_id", models.IntegerField(blank=True, null=True)),
                ("changes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="items.items",
                    ),
                ),
            ],
        ),
    ]
