# Generated by Django 5.0.6 on 2024-08-22 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_itemsauditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemsauditlog",
            name="changes",
        ),
        migrations.RemoveField(
            model_name="itemsauditlog",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="itemsauditlog",
            name="record_id",
        ),
        migrations.AddField(
            model_name="items",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemsauditlog",
            name="item",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="items.items",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemsauditlog",
            name="observation",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="itemsauditlog",
            name="action",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="itemsauditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
