# Generated by Django 5.0.6 on 2024-08-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_itemsauditlog_changes_itemsauditlog_model_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemsauditlog",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="itemsauditlog",
            name="record_id",
        ),
        migrations.AlterField(
            model_name="itemsauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("Criado", "Criado"),
                    ("Editado", "Editado"),
                    ("Deletado", "Deletado"),
                ],
                max_length=50,
            ),
        ),
    ]
