# Generated by Django 5.0.6 on 2024-08-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0009_remove_itemsauditlog_model_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemsauditlog",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.items",
            ),
        ),
    ]
