# Generated by Django 5.0.6 on 2024-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0010_alter_itemsauditlog_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsauditlog",
            name="item_deletado",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
