# Generated by Django 5.0.6 on 2024-09-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0011_itemsauditlog_item_deletado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="finished_at",
        ),
    ]
