# Generated by Django 5.0.6 on 2024-09-10 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0012_remove_items_finished_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
