# Generated by Django 5.0.6 on 2024-09-10 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0013_alter_items_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
