# Generated by Django 5.0.6 on 2024-09-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0014_alter_items_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="locality",
        ),
    ]
