# Generated by Django 5.0.6 on 2024-09-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0015_remove_items_locality"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="nmr_tombo",
            field=models.PositiveBigIntegerField(
                blank=True, default="0", verbose_name="Tombo"
            ),
        ),
    ]
