# Generated by Django 5.0.6 on 2024-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0016_items_nmr_tombo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="nmr_tombo",
            field=models.PositiveBigIntegerField(blank=True, verbose_name="Tombo"),
        ),
    ]
