# Generated by Django 5.0.6 on 2024-09-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0017_alter_items_nmr_tombo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="nmr_tombo",
            field=models.PositiveBigIntegerField(
                blank=True, default="", verbose_name="Tombo"
            ),
        ),
    ]
