# Generated by Django 5.0.6 on 2024-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0018_alter_items_nmr_tombo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="observation",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Observação"
            ),
        ),
    ]
