# Generated by Django 5.0.6 on 2024-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0019_alter_items_observation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="nmr_tombo",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Tombo"
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="observation",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="Observação"
            ),
        ),
    ]
