# Generated by Django 5.0.6 on 2024-09-19 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0020_alter_items_nmr_tombo_alter_items_observation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemTombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tombo", models.CharField(max_length=50)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tombos",
                        to="items.items",
                    ),
                ),
            ],
        ),
    ]
