# Generated by Django 5.0.6 on 2024-09-19 14:20

from django.db import migrations


def migrate_data(apps, schema_editor):
    Items = apps.get_model('items', 'Items')
    ItemTombo = apps.get_model('items', 'ItemTombo')

    for item in Items.objects.all():
        if item.nmr_tombo is not None:
            # Converte o valor de nmr_tombo para string e cria uma instância de ItemTombo
            ItemTombo.objects.create(item=item, tombo=str(item.nmr_tombo))

class Migration(migrations.Migration):

    dependencies = [
        ("items", "0021_itemtombo"),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
