# Generated by Django 5.0.6 on 2024-09-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0022_auto_20240919_1120"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="nmr_tombo",
        ),
    ]
