# Generated by Django 5.0.6 on 2024-09-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0023_remove_items_nmr_tombo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="observation",
            field=models.CharField(
                blank=True, default="", max_length=600, verbose_name="Observação"
            ),
        ),
        migrations.AlterField(
            model_name="itemtombo",
            name="tombo",
            field=models.CharField(max_length=200),
        ),
    ]
