# Generated by Django 5.0.6 on 2024-06-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_todo_options_alter_todo_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="category",
            field=models.CharField(
                default="Geral", max_length=100, verbose_name="Categoria"
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="quantity",
            field=models.IntegerField(
                default=0, verbose_name="Quantidades de Unidades"
            ),
        ),
    ]
