# Generated by Django 5.0.6 on 2024-06-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_todo_category_todo_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={},
        ),
        migrations.RemoveField(
            model_name="todo",
            name="deadline",
        ),
    ]
