# Generated by Django 5.0.6 on 2024-06-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0006_alter_todo_options_remove_todo_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="category",
            field=models.CharField(default="Opção Padrão", max_length=100),
        ),
    ]
