# Generated by Django 5.0.6 on 2024-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0007_alter_todo_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="category",
            field=models.CharField(
                default="Opção Padrão", max_length=100, verbose_name="Categoria"
            ),
        ),
    ]
